"""add shoppingitem model

Revision ID: 5d3ed30e351e
Revises: ad4a9857282d
Create Date: 2026-07-18 15:23:19.747208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3ed30e351e'
down_revision: Union[str, Sequence[str], None] = 'ad4a9857282d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fooditem_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_needed', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fooditem_id'], ['food_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_items_id'), 'shopping_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_items_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    # ### end Alembic commands ###
