"""add Inventory Location model

Revision ID: e07eaacc2e4f
Revises: e68a1d81ca23
Create Date: 2026-07-18 14:54:22.016676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07eaacc2e4f'
down_revision: Union[str, Sequence[str], None] = 'e68a1d81ca23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('style', sa.JSON(), nullable=True))
    op.add_column('categories', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('metadata_keys', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'metadata_keys')
    op.drop_column('categories', 'description')
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'style')
    # ### end Alembic commands ###
