"""add Inventory Location model

Revision ID: e68a1d81ca23
Revises: f316233567ed
Create Date: 2026-07-18 14:38:28.160637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68a1d81ca23'
down_revision: Union[str, Sequence[str], None] = 'f316233567ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_locations', sa.Column('type', sa.String(), nullable=False))
    op.add_column('inventory_locations', sa.Column('emoji', sa.String(), nullable=False))
    op.add_column('inventory_locations', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_locations', 'description')
    op.drop_column('inventory_locations', 'emoji')
    op.drop_column('inventory_locations', 'type')
    # ### end Alembic commands ###
